# Generated by Django 2.1.8 on 2019-10-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='age',
            field=models.IntegerField(),
        ),
    ]
